### ISSUE TITLE
EAF file to test for quotes added

### ISSUE THREAD

**Issue by davidjamesbeck** [paul-shannon/slexil#16]
I added a folder with a Chatino file containing various error with quotes. I can try to write a test file for this—would it be a standalone file like text_text_prayer.py or should I just add something to one of the exisiting files?

**Comment by paul-shannon** [comment]
This is a really good addition - thanks, David.

Let’s mull over where to put

  - the code which detects and corrects for quote (and spacing? and etc?) errors
    (which I think of as author infelicities)

  - the test for that code

Here are some preliminary thoughts.  Feel free to suggest other options.

In the IjalLine class (ijalLine.py), most of the work is done in the constructor (“__init__”) and the parse method.   The constructor  calls

   self.tblRaw = buildTable()

and the parse method calls 

   self.tbl = standardizeTable(self.tblRaw, self.tierGuide)

Then tests/test_IjalLine.py has a function

   test_buildTable()

With all of this in mind, I propose we add a new method to the IjalLine class, and a new test for that method in tests/test_IjalLine.py:

   self.tbl = standardizeAuthorTextInTiers(self.tbl)  # updates and improves this pandas table

This could take the result of standardizeTable as input, then clean up all the author’s infelicitous uses of EAF. tests/test_IjalLine.py  would then get additional tests, checking for proper cleanup of all the infelicities we accumulate:
 
    test_standardizeAuthorTextInTiers_infelicity_1()

These tests would then be a lot like test_buildTable, but just go a bit further.
Tell me what you think.  

May I also ask you to rename “Chatino_2Line” so that the purpose of that test project is clear?  Something like
Chatino_FaultyAuthorTextExamples - you can probably come up with something better.   I try to achieve the goal, in all naming (variables, classes, files, directories), of maximum clarity, good self-documentation.

  git mv oldDirName newDirName
  git commit -m “some commit message here”
  git push

I hope I am not being too bossy.

 - Paul

**Comment by davidjamesbeck** [comment]
Hi, Paul

The folder I added was Chatino_quotes. After several false starts, I managed to rename it to the name you suggested and push it. Hopefully it is there now.

What you say below sounds okay to me. It makes sense to me to have the method that cleans up the translation lines in the IjalLine class. Another way to go would be to make the clean up part of a TranslationLine class (like the MorphemeGloss class). That might be overkill in terms of complexity, though, to define a new independent class for something that is probalby not very complex in and of itself. I’m not really in a position to judge what’s better programming practice.

cheers,

David

**Comment by paul-shannon** [comment]
I like the idea of a TranslationLine class.   Is it only in that tier that problems with quotes and spaces occur?  Not in the spokenText tier?   

Would it help if I created an initial skeletal version and failing tests?  Which you could then elaborate into truly functional code?

**Comment by davidjamesbeck** [comment]
The translation tier would be the only tier that needs standardization of the single quotes on either side. Ideally, the other tiers would be stripped of leading and trailing whitespace. I can’t think of other general clean up the spokenText tier might need. There’s going to be a lot of variation, especially since there will be a variety of orthographies and punctuation systems represented. It is probably safest to leave it up to authors to police that line. 

When it comes time to create an optional second translation tier, we’d probably just want to subclass the primary translation tier, and we’d get the clean up routines for free. Some of the potential secondary languages, like Spanish, have slightly different punctuation practices when it comes to direct speech, but I’m not sure I’d want us to be reponsible for that (unless, say, there is a Python module already written for mapping English punctuation to other languages—but even then, I think that would just be showing off).

The sixth line, an optional additional transcription or possibly something else, should probably be left as underspecified as possible—no leading or trailing whitespace, but beyond that probably nothing.

If you sketch this out and make a template for the tests, that would help. I’m starting to see how the dependencies work between the various test files and this will help.

David

**Comment by paul-shannon** [comment]
@davidjamesbeck 
I just added two files to the repo:
 -   translationLine.py:  defines a rudimentary TranslationLine class
 -  tests/test_TranslationLine.py:  reads in your nine lines from Chatino_FaultyAuthorExamples, asks the TranslationLine class to standardize the line.

This small class and its tests do not yet work.  I offer them as structure - minimal structure - in which you can work out the proper standardization code for the 9 faulty cases you provide, and to test the results. 

The test extracts your 9 cases from the eaf xml file.   A successful test is stubbed out as a regular expression which every standardized translation line is expected to match.   You may choose to abandon the regex approach - sometimes it is more trouble that it is worth.

 The goal is to create the capability to standardize translation lines in isolation from all of the other code so that then it can be painlessly slipped into the whole system - perhaps in the IjalLine class.

**Comment by davidjamesbeck** [comment]
Hi, Paul

I pulled the new files and looked them over. At this point what you’d like me to do is to add some code to the TranslationLine class, in the standardize() method, to clean up the problems I created in the translations in the new EAF file, right? Do you want me to open a new git branch for that?

BTW, I notice you define rawText and cleanText as empty string variables in the TranslationLine class. I didn’t think that was necessary in Python?

David

**Comment by paul-shannon** [comment]
Hi David,

You captured my hopes exactly - with maybe one addition:  write the tests first, with a do-nothing standardize method, make sure they fail, then write your standardizing code, watch as the tests progressively pass.  I would start with the simplest fix first.  Explore gingerly, growing the code one tentative step at a time.

No need to branch the repo.   Your work in translationLine.py and test_TranslationLine.py will not affect anything else - until all tests pass, and you add a call to the class in ijalLine.py.   Branching would be overkill - and is always a pain to manage (for me, anyway).

You are no doubt right about my probably superfluous initialization of the class member data variables.   I tend to forget those details as I switch between languages.   And so I fall back on explicitness.   Feel free to change the code to be more pythonic.

Let me know how the work goes.   I mention in the code that regex tests may be excessive:  hard to come up with, finicky to adjust.   A simple brute force check of the cleaned up line could probably be accomplished with a succession of simple questions:

  - opening curly quote to start?  closing curly quote at end?
  - no leading or trailing white space?
  - equal number of double quote characters, when used?

and so on…

Cheers!

- Paul

**Comment by davidjamesbeck** [comment]
Hi, Paul

> On Mar 27, 2019, at 2:05 PM, Paul Shannon <notifications@github.com> wrote:
> 
> Hi David,
> 
> You captured my hopes exactly - with maybe one addition: write the tests first, with a do-nothing standardize method, make sure they fail, then write your standardizing code, watch as the tests progressively pass. I would start with the simplest fix first. Explore gingerly, growing the code one tentative step at a time.

I’m not sure I follow about writing the tests separately—all the different failing conditions are in the new EAF file, so we keep getting assertion errors when we run tests on that file until all nine conditions are accounted for. But since the test supplies verbose output, we can track the each error as it gets solved (that is, the first translation uses apostrophes instead of quotes, so the assertion in the test file fails on first pass; that gets fixed and then the next line fails because it has leading and trailing white space; that gets fixed, etc.). This will happen because your REGEX seems identify a string that starts and ends with single quotes, and I think that all 9 errors in the EAF file would be caught by that. 

I guess when it comes to double quotes, we’d need a new EAF file with new errors—so there I can see writing a new test file because we need new assertions to test for those errors. So new test file if we need new input or new assertions. Or am I just hopelessly confused?
> 
> No need to branch the repo. Your work in translationLine.py and test_TranslationLine.py will not affect anything else - until all tests pass, and you add a call to the class in ijalLine.py. Branching would be overkill - and is always a pain to manage (for me, anyway).

Fine by me. I actually got hold of a GIT app and managed to see the history of my first feeble attempts at using branches. Not pretty at all.
> 
> You are no doubt right about my probably superfluous initialization of the class member data variables. I tend to forget those details as I switch between languages. And so I fall back on explicitness. Feel free to change the code to be more pythonic.

I’m not concerned about being pythonic, I was just wondering if there was a reason you might want to have done that (I think it would cause an error if something other than a string was fed to the __init__() method when the construtor was called, wouldn’t it? If so, there might have been method in your madness—there rarely is in mine, but I like to give people the benefit of the doubt). I am doing my best to capitalize on seeing how someone who knows what they are doing does things.

David
> 
> Let me know how the work goes. I mention in the code that regex tests may be excessive: hard to come up with, finicky to adjust. A simple brute force check of the cleaned up line could probably be accomplished with a succession of simple questions:
> 
> - opening curly quote to start? closing curly quote at end?
> - no leading or trailing white space?
> - equal number of double quote characters, when used?
> 
> and so on…
> 
> Cheers!
> 
> - Paul
> 
>

**Comment by paul-shannon** [comment]
> 
> I’m not sure I follow about writing the tests separately

The useful dogma here is: write tests before (or maybe AS you write the code).   This means that you avoid the cardinal sin: the intention to write tests after the code is developed - an intention which is never accomplished.

And the most important coding practice is that the tests specify what the code does.  No-one ever writes code without testing it somehow - even if just minimally, from the command line, then concluding “that works”.

Tests just formalize this a little.  You have a test - some criterion of success - in mind.  So don’t just keep it in your head: write in into a re-runnable test script.  That’s the basic idea.   When you want to add code to translationLine.py which removes white space, do these things:

 in test_TranslationLine.py, add a new function

    def test_removeWhiteSpace()
       faulty = “   abcd   efg   “
       expected = “abcd   egg”
       line = TranslationLine(fault)
       line.standardize()
       assert(line.getClean() == expected)

Write this first.   It should run fine - up until the assertion fails.   Even that failure accomplishes a lot.  You have to have worked out how to call the constructor.   You test for the existence of the standardize and getClean methods.  Then you add the bit of logic which actually does the standardization.  Rerun the test.  Now it passes - or will soon, after you evolve the logic to truly do the job which the test requires.

       

You mention needing a new faulty author-provided translation line to exemplify ill-used double quotes.  I suggest

  1) add a new line to Chatino_FaultyAuthorExamples/20150717_Prayer_community_one.eaf
  

You might want to forgo (and delete) all the other files in that directory.  You’ll see how in my test_TranslationLine.py I read the xml tiers directly.  If the faulty test directory has only the eaf file, it will be easier to add new faulty cases:  no audio to change, no use of ELAN needed.  The one concession to standards made here is that the faulty lines are actually obtained from a valid eaf file - so that we know that we are reading them in a native form, very close to what our other code will eventually do.  The one eaf file allows us to capture each faulty translation line variant “in the wild”.   

  2) maybe write multiple small test functions in test_TranslationLine.py - one for each
     error case you have identified.

I wrote it like this:

   test_standarizeTranslationLine()

better would be something like

   def test_missingFinalQuote()
   def test_missingCurlyQuotes() 
   def test_leadingWhiteSpace()
   ...

then solve them one at a time, adding them, when you want to include them, in 

def runTests():
    test_missingFinalQuote()      # get this test working first
    # test_missingCurlyQuotes()    
    # test_leadingWhiteSpace()

**Comment by davidjamesbeck** [comment]
Okay, I see. I was thinking each test would be a new .py file. That also explains why the other, more venerable test files for IjalLine you’d written were so complex. I’ll just add a new method that tests each error in the EAF file until all 9 are taken care of.

David

**Comment by davidjamesbeck** [comment]
I think that this is now complete, at least insofar as I can't think of any more permutations of incorrect use of quotes to test
