### ISSUE TITLE
prettifying UI

### ISSUE THREAD

**Issue by davidjamesbeck** [paul-shannon/slexil#20]
I assume that Dash will allow us to start presenting this in a slicker format. Is it time to think about page presentation? I'm guessing there's somewhere we can build a stylesheet and I can work on a header and text to live at the top of the page. I'm not clear on where/how this kind of thing is done, though.

**Comment by paul-shannon** [comment]
Here’s the technique for adding local (our own) css to the app:

   https://dash.plot.ly/external-resources

**Comment by davidjamesbeck** [comment]
Cool, thanks. I’ll have a look and play with it a bit. Unless there’s something else you’d like me to work on first.

David

**Comment by paul-shannon** [comment]
Hi David,

As much as possible I wish now to shift to only an advisory role.   I will jump back into coding when it is needed but hope that I can mostly Tom-Sawyer you into all of that.

The actual deployment on your university’s website should not pose a huge challenge IF the university’s computing group helps out, which is a reasonable thing to ask them to do.   Since we have used standard languages and libraries throughout, that might be glad to help.

One aspect of alexis which will need some work is handling errors in tier assignment.  It might be as simple as wrapping the server side code - that which first tries to use the tiers - in a try/catch block, then posting an error dialog to the user explaining the general nature (tier misassignment) and ask them to try again.

Mixing up tiers, and mis-specifying line vs tab morpheme packing, will both wreak havoc.

 - Paul

**Comment by davidjamesbeck** [comment]
Sure, that is fine—I think I understand the code well enough to make the final fixes we need. Though maybe one thing I could get you to do is the continuous-playback animation? You mentioned that you thought it would be fairly trivial but didn’t like the way the current Javascript implements that playback. For me the task is potentially doable but doesn’t fall into the category of “trivial”. 

For deployment, then, what would the nuts-and-bolts steps be? Simply sftp the slexil folder to the directory they’ve created for us and ask them to “turn it on”?

On the homestretch!

David
