### ISSUE TITLE
add animated playback of all lines in succession

### ISSUE THREAD

**Issue by paul-shannon** [paul-shannon/slexil#21]
- start, pause, stop buttons
- use addClass, removeClass to highlight success elements, so actual appearance is controlled by css, easily changed
- anything else?

**Comment by paul-shannon** [comment]
Hi @davidjamesbeck 

I made some progress with serial playback of all the lines in a story.  Promises, async, await, resolve - all of these had me confused for a while.   

Take a look at  ````slexil/explorations/playAudioInSequence/playAudioInSequence.html````

Deficits:
   - there is no animation css
   - you cannot interrupt a sound once it starts playing
   - playback always starts at the first line
   - I have not moved the code into ````ijalUtils.js````

But the tricky parts are now working well.  

Can you take it from here?

**Comment by davidjamesbeck** [comment]
Hi, Paul

Okay, I’ll take a look and see if I can figure it out. Is there a good source for the audio playback methods in Java?

I sent a merge request for the last tweaks I made on the workflow control branch.

**Comment by paul-shannon** [comment]
Hi David,

This will give you a bunch of good starting points:

https://www.google.com/search?q=html5+audio&oq=html5+audio&aqs=chrome..69i57j69i59.2951j0j4&sourceid=chrome&ie=UTF-8

The audio tag itself is pretty straightforwards.  Serial playback was the bugbear, now I think solved.

Adding pause and mid-sound stop is not so hard with a single sound.   It might take some fancy footwork to support those two operations in the midst of async and promises. 

You would probably need to keep a global state object - call it “currentSoundElement” which you can pause and stop (those operations are supported in html5 I am pretty sure).   But how that interacts or does not interact with the serial playback async/promise queue may get dicey.

I can make an altogether predictable suggestion :}   Which is to call single and serial playback good enough, with “stop” supported at the end of the current sound - then get to the more fine-grained control later.  

 - Paul

**Comment by davidjamesbeck** [comment]
Hi, Paul

I want to begin this by making an abject apology because I feel like I wasted a bunch of your time, and it was entriley my fault that this happened because a) I didn't really communicate very clearly what the animated playback was all about and b) I overestimated how difficult the task was going to be and really shouldn't have bothered you with it at all. So, let me explain.

As you'll see from my current test project (in Projects/Monkey) and the IjalUtils.js file there, I ended up abandoning the approach you were taking to the playback problem. This is because there's no way users were going to accept playback based on the sequential playing of the audio chunks we are using for individual lines. Users will want to hear the full, fluid text as spoken in the original recording, and even if in theory it might be possible to recreate that, it seemed better just to use the full recording, pre-parsing. So, first apology is that I should have realized that that wouldn't be an assumption you would make, coming from the problem from a software engineer's perspective.

So, what I did was go back to the <audio> tag controls in HTML5—and here's where I feel like I really have egg on my face. When I first adapted Cuped for my own use, it was using Flash and I immediately turfed that for the HTML5 <audio> player (which was too new for the orignal implementation of Cuped). I did a poor job of that and just stuck with a lot of the complicated code that Cuped was using to create and manipulate a Flash player (most of which probably wasn't even doing any work) without really exploring the functionality of the <audio> tag. As it turns out, it does almost everything we needed for playback control, and setting up the animation turned out to be pretty trivial. I really should have known that, especially since when I first looked into <audio> I remembered thinking that it should be possible to simplify the Cuped player.js considerably. So, my second apology is for asking you to help and spend time on a task that was actually pretty straightforward.

Anyway, the animation seems to be working except for two things that I actually do need some advice about. I'll start an issue for each one.

David

**Comment by paul-shannon** [comment]
Thanks for all this, David, but for an apology, there is no need.  Truly.  False starts, changes in direction, new ideas: that’s what we do!

I am now back to “How Daylight was Stolen”.  And I have my first question for you, perhaps best presented visually:



This is from my old (2017) idiosyncratic version of my code.  Much of it should be tossed out in favor of the new. 

But displayed in the image above is one feature which, as a student of the language, I find very valuable: popups which display dictionary entries.  In this case, I edited the dictionary entry, reducing it to a short description.  Here’s another one:



In this case, I may have crafted the explanatory text from various readings as well as from the Lushootseed Dictionary as I tried to make sense of the s- prefix.  

Any ideas on how I could add Lushootseed Dictionary entries to an eaf version of How Daylight was Stolen?

 - Paul

**Comment by davidjamesbeck** [comment]
Hi, Paul

I didn’t get the image, but I think I have an idea of what you’re after—something like a tooltip which, maybe on “hover”, pops up some metadata about a word or affix? I don’t think ELAN has the capacity to do that itself (I’m not an ELAN master, but it is mostly an annotation tool, not a presentation tool), so you’d probably be looking at something very like slexil that goes from ELAN to HTML and adds the popups programmatically. You might be able to facilitate this by defining ELAN tier types that would be targeted by a program, so you could read the ELAN file, pull out all the tier types (say, morpheme glosses) and then look up the values of those in a database to get the contents of the pop ups (assuming your morpheme glosses are done with a fixed vocabulary corresponding to lexical entries in the database). 

I currently don’t have a presentable Lushootseed lexical database that might be a good backend for something like this, otherwise I would happily share it with you. Other than my texts, my Lushootseed corpus is trapped in some long-deprecated software, and a project that I may actually get to soon is to recreate that database (which is also deprecated in an analytical sense) based on the texts in their more up-to-date forms. That will become the basis for an actual lexical database, but probably not in the immediate future.

There is a PhD student at UW, Joshua Crowgey, who is finishing up a dissertation on parsing Lushootseed texts. If you’re interested, I could put you in touch with him. He might have something useful. There is a computation linguist at Brigham Young, Derlye Lounsbury, who actually has an electronic version of the Lushootseed Dictionary (and he used to have an online interface, I’m not sure it is still there), but he says that the material is copyrighted to UW Press and so doesn’t pass it around.

Anyway, anything I can do to help, I’ m more than happy to.

Cheers,

David

**Comment by paul-shannon** [comment]
Thanks for these offers, David,

 I’ll defer on all of them for now because, however worthy and fruitful they may be, they would likely divert me from the specific lines, the agglutinations which so delight me in the Harry Moses story.

I will experiment with a bit of javascript add-on, some post-processing that grafts the popups into the html produced by slexil whenever my ad hoc reference collection has an entry for a word or an affix.   I’ll be building that reference collection from multiple sources - making my own synthesis - which will be instructive, and which skirt some of the constraints of the copyrighted Lushootseed Dictionary, especially in that it will probably be just for my own use.

Can I turn to you now and again on questions of grammar?

 - Paul

**Comment by davidjamesbeck** [comment]
Absolutely.

David
